version: '3'
services:
  mysql-db:
    container_name: mysql-docker
    image: plink/mysql-57-centos7
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai     # 指定时区
    stdin_open: true
    tty: true

  plink:
    container_name: plink-docker
    image: hairless/plink:master
    ports:
      - "8081:8081"
      - "8666:8666"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai     # 指定时区
    stdin_open: true
    tty: true
