server:
  port: 8666

logging:
  file:
    name: log/app.log

spring:
  thymeleaf:
    prefix: "classpath:/static/"
  datasource:
    url: jdbc:mysql://silence:3306/plink?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.github.hairless.plink.dao.conf.DataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000t

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.github.hairless.plink.model
  configLocation: classpath:config/mybatis-config.xml


#热部署组件
devtools:
  livereload:
    enabled: true #是否支持livereload
    port: 8666
  restart:
    enabled: true #是否支持热部署

flink:
  restful:
    ip: localhost
    port: 8081